### ISSUE TITLE
[Feature Request] - Make usage of SmbClient thread safe

### ISSUE THREAD

**Issue by RouHim** [veeso/pavao#2]
## Description

I haven't looked closely at the underlying structure of the SmbClient, but is it possible to use this safely in a multi thread context?

I'm receiving this error:
```rust
*mut pavao::libsmbclient::_SMBCCTX cannot be shared between threads safely
```

**Comment by veeso** [comment]
Unfortunately as stated by the author of libsmbclient, the library has no plan to be thread safe, so pavao cannot be either.
