### ISSUE TITLE
[QUESTION] - samba version support

### ISSUE THREAD

**Issue by 0323pin** [veeso/pavao#5]
Hi,

Before I try to fix `termscp` build on NetBSD, https://github.com/veeso/termscp/issues/189

I would like to ask if the following is valid or simply outdated?

> Pavão  is a Rust client library for SMB version 2 and 3 ...

I was trying to link `termscp` to `samba` 4.

**Comment by veeso** [comment]
It probably works with smb 4 as well.

**Comment by 0323pin** [comment]
I'll try when I find the time

**Comment by 0323pin** [comment]
@veeso would it be possible to have smb-support as a optional feature? I'm fine with it being ON by default, I can switch it off at build time.

The reason for this is `pavao` lack of support for non-Linux *nix platforms but, also the uncertainty related to it's support (or, not) for samba4.

As is, the NetBSD package is stuck at v0.11.3
Not a big issue for now but, it will eventually bit rot which, is far from ideal.

Another option is for me to drop the package which, is also far from ideal.

Thoughts?

Regards

**Comment by veeso** [comment]
I'm working on it in the termscp repo
