### ISSUE TITLE
[Feature Request] - Add support for Linux RISC-V64

### ISSUE THREAD

**Issue by moui0** [veeso/pavao#7]
## Description

Add support for Linux RISC-V64.

### Changes

Use `libc::stat` of Linux RISC-V64.

## Implementation

Add conditional compilation option for the relevant fields in `From` trait of `SmbStat`.

**Comment by moui0** [comment]
Hi, if you think that is ok, I could open a PR for this.

**Comment by veeso** [comment]
Hi, yes please, sorry but I don't have much time and I don't have anything to test this change
