### ISSUE TITLE
[BUG] libsmbclient not thread safe

### ISSUE THREAD

**Issue by jackpot51** [veeso/pavao#8]
libsmbclient is not thread safe. To help aleviate potential issues when using this library from multiple threads, I would recommend to wrap libsmbclient calls in a mutex. If desired, I can make those changes. For reference, see libsmbclient-go's use of a mutex: https://github.com/mvo5/libsmbclient-go/blob/master/libsmbclient.go#L58

**Comment by veeso** [comment]
it should now be thread safe

**Comment by jackpot51** [comment]
Awesome, thanks!
