### ISSUE TITLE
[BUG] - Library not loaded: /opt/homebrew/opt/samba/lib/libsmbclient.inst.dylib

### ISSUE THREAD

**Issue by bcarnazzi** [veeso/pavao#9]
## Description

When running `cargo run --example tree -- -u username -w workspace -s share -P password smb://hostname`, I got the following error message : 

Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/examples/tree -u username -w workspace -s share -P password 'smb://hostname'`
dyld[18252]: Library not loaded: /opt/homebrew/opt/samba/lib/libsmbclient.inst.dylib
  Referenced from: <21F9557B-B137-3784-B4CB-8935ACB22CFC> /Users/bcarnazzi/dev/rust/pavao/target/debug/examples/tree
  Reason: tried: '/opt/homebrew/opt/samba/lib/libsmbclient.inst.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/samba/lib/libsmbclient.inst.dylib' (no such file), '/opt/homebrew/opt/samba/lib/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/dev/rust/pavao/target/debug/deps/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/dev/rust/pavao/target/debug/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/.rustup/toolchains/stable-aarch64-apple-darwin/lib/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/lib/libsmbclient.inst.dylib' (no such file), '/usr/local/lib/libsmbclient.inst.dylib' (no such file), '/usr/lib/libsmbclient.inst.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/samba/4.19.4/lib/libsmbclient.inst.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/samba/4.19.4/lib/libsmbclient.inst.dylib' (no such file), '/opt/homebrew/Cellar/samba/4.19.4/lib/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/dev/rust/pavao/target/debug/deps/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/dev/rust/pavao/target/debug/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/.rustup/toolchains/stable-aarch64-apple-darwin/lib/libsmbclient.inst.dylib' (no such file), '/Users/bcarnazzi/lib/libsmbclient.inst.dylib' (no such file), '/usr/local/lib/libsmbclient.inst.dylib' (no such file), '/usr/lib/libsmbclient.inst.dylib' (no such file, not in dyld cache)
zsh: abort      cargo run --example tree -- -u username -w workspace -s share -P password

## Steps to reproduce

brew install samba && brew install pkg-config
git clone https://github.com/veeso/pavao.git
cd pavao
cargo run --example tree -- -u username -w workspace -s share -P password

## Expected behaviour

An example program error because of the erroneous arguments, but not a library loading error

## Environment

- MacOS 14.3
- aarch64
- Rust version 1.75.0
- homebrew 4.2.7
- samba 4.19.4 (bottled)

## Additional information

N/A

**Comment by veeso** [comment]
README!

**Comment by veeso** [comment]
README!

https://github.com/veeso/pavao?tab=readme-ov-file#macos-

MacOS 🍎
Install samba with brew:

brew install samba

**Comment by bcarnazzi** [comment]
> README!
> 
> https://github.com/veeso/pavao?tab=readme-ov-file#macos-
> 
> MacOS 🍎 Install samba with brew:
> 
> brew install samba

samba is already installed with homebrew

**Comment by veeso** [comment]
ha ok, I see. It's an issue of ARM mac devices.

Try this, but I can't help more. It's an issue of how brew installs C library on arm macs.
https://apple.stackexchange.com/questions/414622/installing-a-c-c-library-with-homebrew-on-m1-macs

**Comment by bcarnazzi** [comment]
Yes, it could be the point. I'll test it and let you know

**Comment by mpowell90** [comment]
I'm also running macos aarch64 and experienced this issue, I fixed it by copying the `libsmbclient.dylib` file into the same directory and renaming it `libsmbclient.inst.dylib`. After that it just worked.
